spring:
  application:
    name: rest-service-4
server:
  port: 8082
app:
  version: '0.0.1-SNAPSHOT'
build:
   timestamp: '@build.time@'
properties:
   myown:
      version:
         old: 'version-1.0.0'
         new: 'version-1.0.1'