spring:
  application:
    name: rest-service-1
server:
  port: 8080
app:
  version: '@project.version@'
build:
   timestamp: '@build.time@'
properties:
   myown:
      version:
         old: 'version-1.0.0'
         new: 'version-1.0.1'