spring:
  application:
    name: rest-service-2
server:
  port: 8081
app:
  version: '@project.version@'
build:
   timestamp: '@build.time@'
properties:
   myown:
      version:
         old: 'version-1.0.0'
         new: 'version-1.0.1'
  